version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      # this group of dependencies go together, pending this issue: https://github.com/dotnet/runtime/issues/81395
      testplatform:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.TestPlatform.ObjectModel"